version: 2
jobs:
  test:
    docker:
      - image: circleci/node:12
        environment:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_NAME: nest-todo
          DB_USER: nest
          DB_PASSWORD: 123

      - image: circleci/postgres
        environment:
          POSTGRES_USER: nest
          POSTGRES_PASSWORD: 123
          POSTGRES_DB: nest-todos

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: yarn install

      - run:
          name: Run test
          command: npm run test:e2e

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
